const GET_BOND_DATA_PENDING = "GET_BOND_DATA_PENDING";
const GET_BOND_DATA_SUCCESS = "GET_BOND_DATA_SUCCESS";
const GET_BOND_DATA_ERROR = "GET_BOND_DATA_ERROR";

export { GET_BOND_DATA_PENDING, GET_BOND_DATA_SUCCESS, GET_BOND_DATA_ERROR };
